services:
  backend:
    build: ./backend
    container_name: devsecops-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      retries: 5
  frontend:
    build: ./frontend
    container_name: devsecops-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: postgres:15
    container_name: devsecops-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
